import type { AgentAdapterType, CompanyStatus, PauseReason } from "../constants.js";

export interface Company {
  id: string;
  name: string;
  description: string | null;
  status: CompanyStatus;
  pauseReason: PauseReason | null;
  pausedAt: Date | null;
  issuePrefix: string;
  issueCounter: number;
  budgetMonthlyCents: number;
  spentMonthlyCents: number;
  requireBoardApprovalForNewAgents: boolean;
  brandColor: string | null;
  voiceDescription: string | null;
  targetAudience: string | null;
  defaultChannel: string | null;
  defaultGoal: string | null;
  voiceExamplesRight: string[];
  voiceExamplesWrong: string[];
  mailchimpDefaultListId: string | null;
  mailchimpDefaultTemplateId: string | null;
  mailchimpDefaultFromName: string | null;
  mailchimpDefaultReplyTo: string | null;
  agentDefaultAdapterType: AgentAdapterType | null;
  agentDefaultProvider: string | null;
  agentDefaultModel: string | null;
  agentDefaultHeartbeatIntervalSec: number | null;
  agentDefaultWakeOnDemand: boolean | null;
  agentDefaultCooldownSec: number | null;
  agentDefaultMaxConcurrentRuns: number | null;
  agentDefaultMaxTurnsPerRun: number | null;
  agentDefaultBrowserAutomationProvider: string | null;
  agentDefaultHermesManagedHome: boolean | null;
  agentDefaultHermesSeedCompanyProfileMemory: boolean | null;
  agentDefaultHermesToolsets: string | null;
  agentDefaultHermesAllowedMcpServers: string | null;
  agentDefaultHermesMcpServers: Record<string, unknown> | null;
  agentDefaultDangerouslySkipPermissions: boolean | null;
  agentDefaultDangerouslyBypassSandbox: boolean | null;
  logoAssetId: string | null;
  logoUrl: string | null;
  createdAt: Date;
  updatedAt: Date;
}
