import { pgTable, uuid, text, integer, timestamp, boolean, uniqueIndex, jsonb } from "drizzle-orm/pg-core";

export const companies = pgTable(
  "companies",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    description: text("description"),
    status: text("status").notNull().default("active"),
    pauseReason: text("pause_reason"),
    pausedAt: timestamp("paused_at", { withTimezone: true }),
    issuePrefix: text("issue_prefix").notNull().default("PAP"),
    issueCounter: integer("issue_counter").notNull().default(0),
    budgetMonthlyCents: integer("budget_monthly_cents").notNull().default(0),
    spentMonthlyCents: integer("spent_monthly_cents").notNull().default(0),
    requireBoardApprovalForNewAgents: boolean("require_board_approval_for_new_agents")
      .notNull()
      .default(true),
    brandColor: text("brand_color"),
    voiceDescription: text("voice_description"),
    targetAudience: text("target_audience"),
    defaultChannel: text("default_channel"),
    defaultGoal: text("default_goal"),
    voiceExamplesRight: jsonb("voice_examples_right").$type<string[]>().notNull().default([]),
    voiceExamplesWrong: jsonb("voice_examples_wrong").$type<string[]>().notNull().default([]),
    mailchimpDefaultListId: text("mailchimp_default_list_id"),
    mailchimpDefaultTemplateId: text("mailchimp_default_template_id"),
    mailchimpDefaultFromName: text("mailchimp_default_from_name"),
    mailchimpDefaultReplyTo: text("mailchimp_default_reply_to"),
    agentDefaultAdapterType: text("agent_default_adapter_type"),
    agentDefaultProvider: text("agent_default_provider"),
    agentDefaultModel: text("agent_default_model"),
    agentDefaultHeartbeatIntervalSec: integer("agent_default_heartbeat_interval_sec"),
    agentDefaultWakeOnDemand: boolean("agent_default_wake_on_demand"),
    agentDefaultCooldownSec: integer("agent_default_cooldown_sec"),
    agentDefaultMaxConcurrentRuns: integer("agent_default_max_concurrent_runs"),
    agentDefaultMaxTurnsPerRun: integer("agent_default_max_turns_per_run"),
    agentDefaultBrowserAutomationProvider: text("agent_default_browser_automation_provider"),
    agentDefaultHermesManagedHome: boolean("agent_default_hermes_managed_home"),
    agentDefaultHermesSeedCompanyProfileMemory: boolean("agent_default_hermes_seed_company_profile_memory"),
    agentDefaultHermesToolsets: text("agent_default_hermes_toolsets"),
    agentDefaultHermesAllowedMcpServers: text("agent_default_hermes_allowed_mcp_servers"),
    agentDefaultHermesMcpServers: jsonb("agent_default_hermes_mcp_servers").$type<Record<string, unknown> | null>(),
    agentDefaultDangerouslySkipPermissions: boolean("agent_default_dangerously_skip_permissions"),
    agentDefaultDangerouslyBypassSandbox: boolean("agent_default_dangerously_bypass_sandbox"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    issuePrefixUniqueIdx: uniqueIndex("companies_issue_prefix_idx").on(table.issuePrefix),
  }),
);
